name: Trigger auto deployment for ecourtsapidevcapp

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: [dev]
    paths:
      - "**"
      - ".github/workflows/ecourtsapidevcapp-AutoDeployTrigger-f74b8816-844a-4c13-862c-1914ee413c4a.yml"

  # Allow mannually trigger
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: ecourtsscrapper.azurecr.io
          username: ${{ secrets.ECOURTSAPIDEVCAPP_REGISTRY_USERNAME }}
          password: ${{ secrets.ECOURTSAPIDEVCAPP_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ecourtsscrapper.azurecr.io/ecourtsapidockerimagecontainer:${{ github.sha }}
          file: ./Dockerfile
          context: ./

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Install jq
        run: |
          sudo apt-get install -y jq

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.ECOURTSAPIDEVCAPP_AZURE_CREDENTIALS }}

      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set \
              -n ecourtsapidevcapp -g ecourts_api \
              --server ecourtsscrapper.azurecr.io \
              --username  ${{ secrets.ECOURTSAPIDEVCAPP_REGISTRY_USERNAME }} \
              --password ${{ secrets.ECOURTSAPIDEVCAPP_REGISTRY_PASSWORD }}
            az containerapp update \
              -n ecourtsapidevcapp -g ecourts_api \
              --image ecourtsscrapper.azurecr.io/ecourtsapidockerimagecontainer:${{ github.sha }}
            OLD_REVISION=$(az containerapp revision list --name ecourtsapidevcapp --resource-group ecourts_api | jq -r '.[0].name')
            az containerapp ingress traffic set -n ecourtsapidevcapp \
              -g ecourts_api --revision-weight latest=100
            az containerapp revision deactivate \
              --revision $OLD_REVISION \
              --resource-group ecourts_api
